services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: foro
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpw
    restart: unless-stopped
    volumes:
      - ./ws/db/schema/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql

  webserver:
    image: golang:latest
    working_dir: /app
    volumes:
      - ./ws:/app
    ports:
      - "8080:8080"
    command: sh -c "go test -v ./... && go run main.go"
    depends_on:
      - db