// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Mensaje struct {
	IDMensaje           int32         `json:"id_mensaje"`
	IDUsuario           sql.NullInt32 `json:"id_usuario"`
	IDRespuestaAMensaje sql.NullInt32 `json:"id_respuesta_a_mensaje"`
	Texto               string        `json:"texto"`
	MeGusta             sql.NullInt32 `json:"me_gusta"`
}

type Usuario struct {
	IDUsuario     int32        `json:"id_usuario"`
	Nombre        string       `json:"nombre"`
	Mail          string       `json:"mail"`
	Contrasenia   string       `json:"contrasenia"`
	FechaCreacion sql.NullTime `json:"fecha_creacion"`
}
