// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Discusion struct {
	IDDiscusion      int32         `json:"id_discusion"`
	Nombre           string        `json:"nombre"`
	IDUsuarioCreador sql.NullInt32 `json:"id_usuario_creador"`
	IDTablero        sql.NullInt32 `json:"id_tablero"`
	IDPrimerMensaje  sql.NullInt32 `json:"id_primer_mensaje"`
}

type Mensaje struct {
	IDMensaje           int32         `json:"id_mensaje"`
	IDUsuario           sql.NullInt32 `json:"id_usuario"`
	IDRespuestaAMensaje sql.NullInt32 `json:"id_respuesta_a_mensaje"`
	Texto               string        `json:"texto"`
	MeGusta             sql.NullInt32 `json:"me_gusta"`
	IDDiscusion         sql.NullInt32 `json:"id_discusion"`
}

type Tablero struct {
	IDTablero      int32          `json:"id_tablero"`
	Nombre         string         `json:"nombre"`
	Descripcion    sql.NullString `json:"descripcion"`
	IDTableroPadre sql.NullInt32  `json:"id_tablero_padre"`
}

type Usuario struct {
	IDUsuario     int32        `json:"id_usuario"`
	Nombre        string       `json:"nombre"`
	Mail          string       `json:"mail"`
	Contrasenia   string       `json:"contrasenia"`
	FechaCreacion sql.NullTime `json:"fecha_creacion"`
}
