// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO Usuario (nombre, mail, contrasenia)
VALUES ($1, $2, $3)
RETURNING id_usuario, nombre, mail, fecha_creacion
`

type CreateUserParams struct {
	Nombre      string `json:"nombre"`
	Mail        string `json:"mail"`
	Contrasenia string `json:"contrasenia"`
}

type CreateUserRow struct {
	IDUsuario     int32        `json:"id_usuario"`
	Nombre        string       `json:"nombre"`
	Mail          string       `json:"mail"`
	FechaCreacion sql.NullTime `json:"fecha_creacion"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Nombre, arg.Mail, arg.Contrasenia)
	var i CreateUserRow
	err := row.Scan(
		&i.IDUsuario,
		&i.Nombre,
		&i.Mail,
		&i.FechaCreacion,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM Usuario WHERE id_usuario = $1
`

func (q *Queries) DeleteUser(ctx context.Context, idUsuario int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, idUsuario)
	return err
}

const getUserById = `-- name: GetUserById :one
SELECT nombre, mail
FROM Usuario
WHERE id_usuario = $1
`

type GetUserByIdRow struct {
	Nombre string `json:"nombre"`
	Mail   string `json:"mail"`
}

func (q *Queries) GetUserById(ctx context.Context, idUsuario int32) (GetUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getUserById, idUsuario)
	var i GetUserByIdRow
	err := row.Scan(&i.Nombre, &i.Mail)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id_usuario, nombre, mail
FROM Usuario
ORDER BY id_usuario
`

type ListUsersRow struct {
	IDUsuario int32  `json:"id_usuario"`
	Nombre    string `json:"nombre"`
	Mail      string `json:"mail"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(&i.IDUsuario, &i.Nombre, &i.Mail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE Usuario SET nombre = $2, mail = $3, contrasenia = $4 WHERE id_usuario = $1
`

type UpdateUserParams struct {
	IDUsuario   int32  `json:"id_usuario"`
	Nombre      string `json:"nombre"`
	Mail        string `json:"mail"`
	Contrasenia string `json:"contrasenia"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.IDUsuario,
		arg.Nombre,
		arg.Mail,
		arg.Contrasenia,
	)
	return err
}
