// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO Usuario (nombre, mail, contrasenia)
VALUES ($1, $2, $3)
RETURNING id_usuario, nombre, mail, fecha_creacion
`

type CreateUserParams struct {
	Nombre      string `json:"nombre"`
	Mail        string `json:"mail"`
	Contrasenia string `json:"contrasenia"`
}

type CreateUserRow struct {
	IDUsuario     int32        `json:"id_usuario"`
	Nombre        string       `json:"nombre"`
	Mail          string       `json:"mail"`
	FechaCreacion sql.NullTime `json:"fecha_creacion"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Nombre, arg.Mail, arg.Contrasenia)
	var i CreateUserRow
	err := row.Scan(
		&i.IDUsuario,
		&i.Nombre,
		&i.Mail,
		&i.FechaCreacion,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id_usuario, nombre, mail, fecha_creacion
FROM Usuario
ORDER BY id_usuario
`

type ListUsersRow struct {
	IDUsuario     int32        `json:"id_usuario"`
	Nombre        string       `json:"nombre"`
	Mail          string       `json:"mail"`
	FechaCreacion sql.NullTime `json:"fecha_creacion"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.IDUsuario,
			&i.Nombre,
			&i.Mail,
			&i.FechaCreacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
